/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud del servicio */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Servicio operativo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear, firmar y enviar un documento electrónico (FE/NCE/NDE)
         * @description Resuelve el tenant por la API key, valida establecimiento/punto, pide el correlativo,
         *     genera el CDC, firma con el certificado descifrado y envía a SIFEN (test o prod según
         *     el prefijo de la key). Persiste el resultado. `201` si SIFEN aprueba (0260); `200` si
         *     rechaza (el detalle va en `data`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDocumentRequest"];
                };
            };
            responses: {
                /** @description Documento rechazado por SIFEN (código distinto de 0260) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponseEnvelope"];
                    };
                };
                /** @description Documento aprobado por SIFEN (0260) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Unprocessable"];
                502: components["responses"]["BadGateway"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{cdc}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emitir un evento de cancelación sobre un CDC */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description CDC (44 dígitos) del documento aprobado a cancelar */
                    cdc: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Error en los datos del documento */
                        motivo: string;
                    };
                };
            };
            responses: {
                /** @description Resultado del evento (REGISTRADO si 0600) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["Unprocessable"];
                502: components["responses"]["BadGateway"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/inutilizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inutilizar un rango de numeración */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InutilizacionRequest"];
                };
            };
            responses: {
                /** @description Resultado del evento (REGISTRADO si 0600) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/panel/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subir .p12 + password en claro (Go cifra y guarda)
         * @description El navegador envía el P12 (base64) y la password en claro. Go cifra con AES-256-GCM
         *     (`ESIGN_MASTER_KEY`) y guarda vía `POST /internal/v1/certificate/store`.
         *     El panel NUNCA cifra ni ve la master key.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PanelCertificateUploadRequest"];
                };
            };
            responses: {
                /** @description Certificado almacenado (cifrado) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/panel/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert timbrado + CSC en claro (Go cifra el CSC y guarda)
         * @description El navegador envía timbrado/CSC en claro. Go cifra el CSC y persiste vía
         *     `POST /internal/v1/environments/store`. Scopeado por ambiente TEST/PROD.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PanelEnvironmentUpsertRequest"];
                };
            };
            responses: {
                /** @description Ambiente actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Unprocessable"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar usuario + negocio (membresía owner) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (devuelve la lista de negocios para elegir) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Usuario + lista de clients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/select-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elegir negocio y emitir el JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user_id: number;
                        client_id: number;
                    };
                };
            };
            responses: {
                /** @description Tokens de acceso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear invitación (base para envío por correo)
         * @description Crea una invitación PENDING con token + expiración. El envío del correo y la aceptación quedan pendientes.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** @enum {string} */
                        role: "owner" | "developer" | "analyst";
                    };
                };
            };
            responses: {
                /** @description Invitación creada (INVITE_PENDING + token) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identidad del negocio + emisor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        /** Upsert del emisor (solo owner) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/establecimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de sucursales con geo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        put?: never;
        /** Alta/actualización de sucursal (solo owner) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EstablecimientoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/establecimientos/{codigo}/puntos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alta/actualización de punto de expedición (solo owner) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Código del establecimiento (ej. 001) */
                    codigo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PuntoExpedicionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert timbrado + CSC cifrado por ambiente (solo owner)
         * @description Recibe el CSC YA cifrado (hex). El panel no debe llamar este endpoint con el CSC en claro:
         *     usar `PUT /v1/panel/environments` en Go (mediación de cifrado).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnvironmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{env}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metadata de timbrado/CSC del ambiente (solo owner, nunca el CSC)
         * @description Devuelve `num_timbrado`, `fecha_inicio_vigencia`, `id_csc`, `key_version` y `has_csc`
         *     para precargar el panel. `data` es `null` si el ambiente todavía no fue configurado.
         *     El CSC (ni cifrado) nunca se expone por este endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    env: "test" | "prod";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["EnvironmentMeta"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de API keys (prefijo/ambiente/estado; nunca la key completa) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{env}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotar la API key de un ambiente (muestra la key UNA sola vez) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    env: "test" | "prod";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key nueva (única vez que se ve completa) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata del certificado ACTIVE (nunca el BLOB) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Subir P12 cifrado + password cifrado (solo owner)
         * @description Recibe ciphertext+nonce YA cifrados. El panel no debe llamar este endpoint con el
         *     P12 en claro: usar `POST /v1/panel/certificate` en Go (mediación de cifrado).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CertificateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Listado paginado de documentos (filtros en el body)
         * @description Endpoint de listado recomendado. Los filtros van en el body porque esta instancia
         *     ORDS no liga query-params de forma fiable (ORDS-25001). `estado`/`tipo` en null no filtran.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        environment: "TEST" | "PROD";
                        /** @enum {string|null} */
                        estado?: "BORRADOR" | "FIRMADO" | "ENVIADO" | "APROBADO" | "RECHAZADO" | "CANCELADO" | null;
                        tipo?: number | null;
                        /** @default 1 */
                        page?: number;
                        /** @default 20 */
                        pageSize?: number;
                    };
                };
            };
            responses: {
                /** @description Listado con meta de paginacion (page/pageSize/total) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [DEPRECADO] Listado por query-params
         * @deprecated
         * @description No usar: los query-params no ligan de forma fiable en esta instancia ORDS (ORDS-25001).
         *     Usar POST /api/v1/documents/search con los filtros en el body.
         */
        get: {
            parameters: {
                query?: {
                    environment?: "TEST" | "PROD";
                    estado?: string;
                    tipo?: number;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{cdc}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cdc: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{cdc}/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar el XML firmado (application/xml) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cdc: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description XML firmado tal cual se envio a SIFEN (regla 0141) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/xml": string;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{cdc}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marcar un documento FIRMADO para reenvio a SIFEN
         * @description Marca `retry_requested=1` en un documento en estado FIRMADO (fallo transitorio de envio).
         *     El worker de Go lo reintenta. Solo aplica a FIRMADO; otros estados devuelven 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cdc: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documento marcado para reenvio */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                400: components["responses"]["Unprocessable"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolver API key → client_id + config + establecimientos */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example sk_test_... */
                        api_key: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/next-number": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correlativo con bloqueo para (est, punto, tipo_de) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        client_id: number;
                        /** @enum {string} */
                        environment: "TEST" | "PROD";
                        establecimiento: string;
                        punto_expedicion: string;
                        tipo_de: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Blobs cifrados del certificado ACTIVE (hex) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        client_id: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/certificate/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persistir P12 cifrado (mediacion Go del panel) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CertificateRequest"] & {
                        client_id: number;
                        /** @default owner */
                        role?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/csc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CSC cifrado (hex) del ambiente para el QR */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        client_id: number;
                        environment: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/environments/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persistir timbrado + CSC cifrado (mediacion Go del panel) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnvironmentRequest"] & {
                        client_id: number;
                        /** @default owner */
                        role?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar/actualizar documento emitido */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/documents/pending-retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Listar documentos FIRMADO pendientes de reenvio (con xml_firmado)
         * @description Usado por el worker de Go. `mode=flagged` solo `retry_requested=1`;
         *     `mode=all` todos los FIRMADO con XML. Bypass VPD (multi-tenant).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default flagged
                         * @enum {string}
                         */
                        mode?: "flagged" | "all";
                        /** @default 50 */
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar evento (cancelacion/inutilizacion) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar una llamada en api_log (lo usa el middleware de Go) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        client_id?: number;
                        environment?: string;
                        endpoint: string;
                        http_status: number;
                        latency_ms: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Envelope estándar de éxito. */
        Envelope: {
            /** @example true */
            success: boolean;
            /** @description Objeto o arreglo con el resultado */
            data?: unknown;
            /** @example null */
            error?: unknown;
            meta?: {
                page?: number;
                pageSize?: number;
                total?: number;
            } | null;
        };
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /** @example null */
            data?: unknown;
            error: {
                /** @example UNAUTHORIZED */
                code?: string;
                /** @example falta Authorization: Bearer ... */
                message?: string;
            };
        };
        HealthResponse: components["schemas"]["Envelope"] & {
            data?: {
                /** @example ok */
                status?: string;
                /** Format: date-time */
                time?: string;
            };
        };
        Geo: {
            /** @example 12 */
            cod?: number;
            /** @example CENTRAL */
            desc?: string;
        };
        ReceptorRequest: {
            /** @enum {string} */
            tipo: "ci" | "ruc" | "innominado" | "extranjero";
            documento?: string;
            /** @description DV (receptor RUC) */
            dv?: number;
            /** @description 1 física, 2 jurídica (RUC) */
            tipoContribuyente?: number;
            /** @description iTiOpe (RUC) */
            tipoOperacion?: number;
            nombre?: string;
            /** @description ISO-3 ≠ PRY (extranjero) */
            pais?: string;
            desPais?: string;
            /** @description iTipIDRec (extranjero) */
            tipoIdentificacion?: number;
        };
        ItemRequest: {
            /** @example SERV-001 */
            codigo?: string;
            descripcion: string;
            /** @example 1 */
            cantidad: number;
            /** @example 150000 */
            precioUnitario: number;
            /**
             * @description 1 gravado, 2 exonerado, 3 exento, 4 parcial
             * @enum {integer}
             */
            afectacionIVA: 1 | 2 | 3 | 4;
            /** @enum {integer} */
            tasaIVA: 10 | 5 | 0;
            unidadMedida?: number;
            desUnidadMedida?: string;
            /** @description gravado parcial */
            propIVA?: number;
        };
        CreateDocumentRequest: {
            /**
             * @example fe
             * @enum {string}
             */
            tipo: "fe" | "nce" | "nde";
            /**
             * @example contado
             * @enum {string}
             */
            condicion?: "contado" | "credito";
            /**
             * @description días (crédito a plazo)
             * @example 30
             */
            plazo?: string;
            datos_operacion?: {
                /** @example 001 */
                establecimiento?: string;
                /** @example 001 */
                punto_expedicion?: string;
            };
            receptor?: components["schemas"]["ReceptorRequest"];
            /** @example PYG */
            moneda: string;
            tipoCambio?: number | null;
            items: components["schemas"]["ItemRequest"][];
            /** @description NCE/NDE: CDC de la factura referenciada */
            cdcRef?: string;
            /** @description NCE/NDE: motivo de emisión */
            motivo?: number;
        };
        DocumentResponseEnvelope: components["schemas"]["Envelope"] & {
            data?: {
                /** @example 01060389648001001000000812026072514730603957 */
                cdc?: string;
                /**
                 * @example APROBADO
                 * @enum {string}
                 */
                estado?: "APROBADO" | "RECHAZADO" | "FIRMADO";
                /** @example 0260 */
                codRes?: string;
                /** @example 49767439 */
                protAut?: string;
                mensaje?: string;
                qr?: string;
                /** @example 0000008 */
                numeroDocumento?: string;
                /** @example test */
                ambiente?: string;
            };
        };
        InutilizacionRequest: {
            /** @example 001 */
            establecimiento?: string;
            /** @example 001 */
            punto_expedicion?: string;
            /** @example 1000 */
            numeroInicial: number;
            /** @example 1005 */
            numeroFinal: number;
            /** @example 1 */
            tipoDE: number;
            motivo: string;
        };
        EventResponseEnvelope: components["schemas"]["Envelope"] & {
            data?: {
                /**
                 * @example REGISTRADO
                 * @enum {string}
                 */
                estado?: "REGISTRADO" | "RECHAZADO";
                /** @example 0600 */
                codRes?: string;
                protAut?: string;
                mensaje?: string;
                /** @example test */
                ambiente?: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            first_name?: string;
            last_name?: string;
            business_name: string;
            ruc: string;
            dv?: number;
        };
        EstablecimientoRequest: {
            /** @example 001 */
            codigo: string;
            denominacion?: string;
            direccion: string;
            /** @example 0 */
            num_casa?: string;
            dep: components["schemas"]["Geo"];
            dis?: components["schemas"]["Geo"];
            ciu: components["schemas"]["Geo"];
            telefono?: string;
            email?: string;
        };
        PuntoExpedicionRequest: {
            /** @example 001 */
            codigo: string;
            /** @example Caja 1 */
            descripcion?: string;
            /**
             * @default 1
             * @enum {integer}
             */
            is_active: 0 | 1;
        };
        /** @description Payload del panel hacia Go. Go cifra antes de persistir. */
        PanelCertificateUploadRequest: {
            /** @description Contenido del .p12 en base64 */
            p12_base64: string;
            /**
             * Format: password
             * @description Password del P12 en claro
             */
            password: string;
            /** @description Opcional; Go puede derivarlo del P12 */
            subject_dn?: string;
            /**
             * Format: date-time
             * @description Opcional; Go puede derivarlo del P12
             */
            not_after?: string;
        };
        /** @description Payload del panel hacia Go. Go cifra el CSC antes de persistir. */
        PanelEnvironmentUpsertRequest: {
            /** @enum {string} */
            environment: "TEST" | "PROD";
            /** @example 06038964 */
            num_timbrado: string;
            /**
             * Format: date
             * @example 2026-07-09
             */
            fecha_inicio_vigencia: string;
            /** @example 0001 */
            id_csc: string;
            /** @description CSC en claro (32 hex chars típicos de SET) */
            csc: string;
        };
        /** @description El CSC llega YA cifrado (hex) por el cliente/Go; ORDS nunca ve el claro. */
        EnvironmentRequest: {
            /** @enum {string} */
            environment?: "TEST" | "PROD";
            /** @example 06038964 */
            num_timbrado?: string;
            /**
             * Format: date
             * @example 2026-07-09
             */
            fecha_inicio_vigencia?: string;
            /** @example 0001 */
            id_csc?: string;
            /** @description hex */
            csc_ciphertext?: string;
            /** @description hex */
            csc_nonce?: string;
            /** @example 1 */
            key_version?: number;
        };
        /** @description Metadata del ambiente configurado. Nunca incluye el CSC (ni cifrado). */
        EnvironmentMeta: {
            /** @example 06038964 */
            num_timbrado: string | null;
            /**
             * Format: date
             * @example 2026-07-09
             */
            fecha_inicio_vigencia: string | null;
            /** @example 0001 */
            id_csc: string | null;
            /** @example 1 */
            key_version?: number | null;
            /** @description true si ya hay un CSC guardado para este ambiente */
            has_csc?: boolean;
        } | null;
        /** @description P12 y password YA cifrados (AES-256-GCM) por el cliente. */
        CertificateRequest: {
            subject_dn?: string;
            /** Format: date-time */
            not_after?: string;
            /** @description hex */
            p12_ciphertext: string;
            /** @description hex */
            p12_nonce: string;
            /** @description hex */
            pwd_ciphertext: string;
            /** @description hex */
            pwd_nonce: string;
            /** @example 1 */
            key_version?: number;
        };
    };
    responses: {
        /** @description No autenticado / token inválido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Sin permiso (rol o key revocada/cliente inactivo) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Recurso inexistente */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Payload válido pero inconsistente (validación de negocio) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Error al comunicarse con SIFEN u ORDS */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
